#!/bin/bash
# $1 == src dir

GREP=`which grep`
# extended grep, don't print filenames, ignore case, recurse subdirs
$GREP -E -h -i -r \
	-e '["=]\d{13,17}\b' \
	-e '["=][0-9a-f]{32}\b' \
	--include="*.java" $1 2>&1 || exit 1
