#!/bin/bash
# $1 == src dir

GREP=`which grep`
# -E extended grep
# -h don't print filenames
# -r recurse subdirs
$GREP -E -h -r \
	-e 'acs-(api|oauth)-(key|secret)-(production|development)' \
	--include="*.java" $1 2>&1 || exit 1
