#!/bin/bash
# $1 == src dir

GREP=`which grep`
# -E extended grep
# -h don't print filenames
# -r recurse subdirs
$GREP -E -h -r \
  -e 'AKIA.{16}' \
  -e '["=][0-9a-zA-Z\+\/]{40}[&"]' \
  --include="*.java" $1 2>&1 || exit 1
